In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt

In [2]:
df= pd.read_csv('../../Data_Files/Project_sample_Data/marketing_data.csv')
df.head()

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumStorePurchases,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Response,Complain,Country
0,1826,1970,Graduation,Divorced,"$84,835.00",0,0,6/16/14,0,189,...,6,1,0,0,0,0,0,1,0,SP
1,1,1961,Graduation,Single,"$57,091.00",0,0,6/15/14,0,464,...,7,5,0,0,0,0,1,1,0,CA
2,10476,1958,Graduation,Married,"$67,267.00",0,1,5/13/14,0,134,...,5,2,0,0,0,0,0,0,0,US
3,1386,1967,Graduation,Together,"$32,474.00",1,1,5/11/14,0,10,...,2,7,0,0,0,0,0,0,0,AUS
4,5371,1989,Graduation,Single,"$21,474.00",1,0,4/8/14,0,6,...,2,7,1,0,0,0,0,1,0,SP

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 28 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   2240 non-null   int64
 1   Year_Birth           2240 non-null   int64
 2   Education            2240 non-null   object
 3   Marital_Status       2240 non-null   object
 4    Income              2216 non-null   object
 5   Kidhome              2240 non-null   int64
 6   Teenhome             2240 non-null   int64
 7   Dt_Customer          2240 non-null   object
 8   Recency              2240 non-null   int64
 9   MntWines             2240 non-null   int64
 10  MntFruits            2240 non-null   int64
 11  MntMeatProducts      2240 non-null   int64
 12  MntFishProducts      2240 non-null   int64
 13  MntSweetProducts     2240 non-null   int64
 14  MntGoldProds         2240 non-null   int64
 15  NumDealsPurchases    2240 non-null   int64
 16  NumWebPurchases      2240 non-null   int64
 17  NumCatalogPurchases  2240 non-null   int64
 18  NumStorePurchases    2240 non-null   int64
 19  NumWebVisitsMonth    2240 non-null   int64
 20  AcceptedCmp3         2240 non-null   int64
 21  AcceptedCmp4         2240 non-null   int64
 22  AcceptedCmp5         2240 non-null   int64
 23  AcceptedCmp1         2240 non-null   int64
 24  AcceptedCmp2         2240 non-null   int64
 25  Response             2240 non-null   int64
 26  Complain             2240 non-null   int64
 27  Country              2240 non-null   object
dtypes: int64(23), object(5)
memory usage: 490.1+ KB

In [4]:
## categorical columns
df.select_dtypes(['object','category']).head()

    Education Marital_Status      Income  Dt_Customer Country
0  Graduation       Divorced  $84,835.00      6/16/14      SP
1  Graduation         Single  $57,091.00      6/15/14      CA
2  Graduation        Married  $67,267.00      5/13/14      US
3  Graduation       Together  $32,474.00      5/11/14     AUS
4  Graduation         Single  $21,474.00       4/8/14      SP

In [5]:
df.select_dtypes('number').head()

,ID,Year_Birth,Kidhome,Teenhome,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,MntSweetProducts,...,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Response,Complain
0,1826,1970,0,0,0,189,104,379,111,189,...,4,6,1,0,0,0,0,0,1,0
1,1,1961,0,0,0,464,5,64,7,0,...,3,7,5,0,0,0,0,1,1,0
2,10476,1958,0,1,0,134,11,59,15,2,...,2,5,2,0,0,0,0,0,0,0
3,1386,1967,1,1,0,10,0,1,0,0,...,0,2,7,0,0,0,0,0,0,0
4,5371,1989,1,0,0,6,16,24,11,0,...,1,2,7,1,0,0,0,0,1,0

## GROUP 1 — EASY / FUNDAMENTAL QUESTIONS (LOWER CRITICALITY, GOOD FOR BASICS)

### A. Basic Summary & Exploration

1. 	    What is the distribution of income?
2. 	    What is the average amount spent on Wines?
3. 	    How many customers accepted each campaign?
4. 	    How many customers complained?
5. 	    What is the average web visits per month?
6. 	    What is the average Recency?
7. 	    Which product has the lowest spending?
8. 	    What is the distribution of total purchases via Web?
9. 	    How many customers have kids vs teens?
10. 	 What are the top 10 customers with highest total spending?